import { wholesaleCatalogueUrl } from './wholesaleContact';
import { siteHref } from './sitePaths';
import type { EnquiryKind } from './EnquiryDialog';

type Props = { onEnquire: (kind: EnquiryKind, category?: string) => void };
const categories = [
  { title: 'Protection', image: 'protection', text: 'Cases, screen protectors and camera protection. Tell us your exact device model and preferred style.' },
  { title: 'Power', image: 'power', text: 'Cables, charging plugs and power banks. Ask about connector type and compatibility before choosing.' },
  { title: 'Audio', image: 'audio', text: 'Earphones, headphones and speakers. Tell us whether you need a wired or wireless connection.' },
];

export function AccessoriesPage({ onEnquire }: Props) {
  return <><section className="hero repairs-hero"><div><p className="eyebrow">ITOP / ACCESSORIES</p><h1>Small things.<br />Big difference<span>.</span></h1></div><div className="hero-copy"><p>Protect it. Charge it. Make it yours.<br />Find the right fit for your everyday tech, with stock and compatibility checked before you visit.</p><button className="button button-dark" onClick={() => onEnquire('Accessories')}>Start an accessory enquiry</button></div></section>
    <section className="accessories service-shelf" aria-label="Accessory categories"><div className="product-grid">{categories.map(item => <article className="product" id={item.title.toLowerCase()} key={item.title}><button className="product-photo" onClick={() => onEnquire('Accessories', item.title)} aria-label={`Enquire about ${item.title.toLowerCase()}`}><img src={siteHref(`assets/${item.image}.png`)} alt={`Illustrative ${item.title.toLowerCase()} accessories; current stock varies`} /></button><div className="product-copy"><h2>{item.title}</h2><p>{item.text}</p><button className="text-button" onClick={() => onEnquire('Accessories', item.title)}>Ask about {item.title.toLowerCase()}</button></div></article>)}</div><p className="image-note">Illustrative products · ask us about current models, colours and prices.</p></section>
    <section className="content-section"><div><p className="eyebrow">THE RIGHT FIT</p><h2>Bring the model.<br />We’ll check the match.</h2></div><div className="service-notes"><p>A case needs the exact model. A cable needs the right connector. A charger needs to suit your device.</p><ul><li>Include the full model name in your enquiry.</li><li>Tell us the connector, colour and quantity you need.</li><li>Ask about tablet, laptop, watch or car accessories too.</li></ul><a className="text-button" href="https://deliveroo.co.uk/menu/london/catford/itop-phones-and-repair-center" target="_blank" rel="noopener noreferrer">Check the Deliveroo listing</a><p className="secondary-copy">Selected items may be available for delivery. Stock, delivery area and fees are shown by Deliveroo.</p></div></section>
  </>;
}

export function WholesalePage({ onEnquire }: Props) {
  return <><section className="hero repairs-hero"><div><p className="eyebrow">ITOP / WHOLESALE</p><h1>Your shop.<br />Well supplied<span>.</span></h1></div><div className="hero-copy"><p>Browse our wholesale WhatsApp catalogue, then request a quote for the products and quantities you need.</p><div className="wholesale-actions"><a className="button button-dark" href={wholesaleCatalogueUrl} target="_blank" rel="noopener noreferrer">Browse WhatsApp catalogue</a><button className="text-button" onClick={() => onEnquire('Trade')}>Request a wholesale quote</button><a className="text-button" href={siteHref('wholesale/apply/')}>Apply for trade supply</a></div></div></section>
    <section className="content-section wholesale-request"><div><p className="eyebrow">A USEFUL PRODUCT LIST</p><h2>More detail.<br />A clearer quote.</h2><p className="visit-note">No account or payment is needed to make an enquiry.</p></div><dl className="request-list"><div><dt>01 / Product</dt><dd>Case, protector, cable, charger or audio accessory. Include a reference if you have one.</dd></div><div><dt>02 / Variant</dt><dd>Device model, connector, colour and any requirements.</dd></div><div><dt>03 / Quantity</dt><dd>How many of each variant, and when you need them.</dd></div><div><dt>04 / Collection or delivery</dt><dd>Tell us your preference. Availability, costs and timing are agreed directly.</dd></div></dl></section>
    <section className="repair-band"><div className="repair-intro"><h2>From list<br />to agreed supply.</h2><p>Pricing and quantities are quoted for your enquiry.</p></div><ol className="repair-steps"><li><span>01</span><h3>Send</h3><p>Your products<br />and quantities.</p></li><li><span>02</span><h3>Review</h3><p>Stock, price<br />and options.</p></li><li><span>03</span><h3>Agree</h3><p>Collection<br />or delivery.</p></li></ol><button className="button button-cyan" onClick={() => onEnquire('Trade')}>Build a quote request</button></section>
    <section className="content-section"><div><p className="eyebrow">TRADE SUPPLY OR TEAM DEVICES?</p><h2>The right route.<br />For your business.</h2></div><div className="service-notes"><p>Buying products for resale? Introduce your business and tell us what you usually need.</p><a className="text-button" href={siteHref('wholesale/apply/')}>Start a trade application</a><p className="support-note">Need repairs, replacement devices or accessories for staff? Use iTop for Business.</p><a className="text-button" href={siteHref('business/')}>Explore iTop for Business</a></div></section>
    <section className="content-section repair-faq"><div><p className="eyebrow">TRADE QUESTIONS</p><h2>Before you<br />place an order.</h2></div><div className="faq-list"><details><summary>Is there a minimum order?</summary><p>Ask about the products and quantities you need. Minimum quantities, pack sizes and trade terms are confirmed with your quote.</p></details><details><summary>Where can I browse products?</summary><p>Use our WhatsApp wholesale catalogue, then include the product names or codes in your quote request. We’ll confirm availability, quantities and your final trade quote.</p></details><details><summary>Can you arrange delivery?</summary><p>Send your location and preferred date. Delivery options, charges and timing are confirmed before an order is agreed.</p></details></div></section>
  </>;
}

export function BuySellPage({ onEnquire }: Props) {
  return <><section className="hero repairs-hero"><div><p className="eyebrow">ITOP / BUY & SELL</p><h1>A new chapter.<br />For your tech<span>.</span></h1></div><div className="hero-copy"><p>Looking for your next device, or ready to move one on? Start with a conversation at iTop in Catford.</p><a className="button button-dark" href="#device-options">Explore your options</a></div></section>
    <section className="device-options" id="device-options" aria-label="Buy or sell a device"><article><span className="eyebrow">01 / BUY</span><h2>Find your<br />next device.</h2><p>Tell us your preferred model, storage and budget. Ask about current used or refurbished devices and their condition.</p><button className="button button-dark" onClick={() => onEnquire('Buy / sell', 'Buy a device')}>Start a buying enquiry</button><p className="secondary-copy">Availability, condition and any warranty are confirmed for the individual device.</p></article><article><span className="eyebrow">02 / SELL</span><h2>See what<br />yours could be worth.</h2><p>Share the model, storage, condition and any faults. An offer depends on an in-store inspection and ownership checks.</p><button className="button button-dark" onClick={() => onEnquire('Buy / sell', 'Sell a device')}>Start a selling enquiry</button><p className="secondary-copy">An enquiry is not a final valuation or a commitment to sell.</p></article></section>
    <section className="content-section"><div><p className="eyebrow">BEFORE YOUR VISIT</p><h2>Know your device.<br />Protect your data.</h2></div><div className="service-notes"><p>Back up your personal files before selling. Bring the device and any relevant accessories or proof of ownership.</p><ul><li>Tell us about damage, battery problems or repairs.</li><li>Ask the team about account and activation locks.</li><li>Discuss reset steps in-store once you agree to sell.</li><li>Never share account passwords or passcodes in your enquiry.</li></ul><a className="text-button" href={siteHref('contact/')}>Visit & Contact</a></div></section>
  </>;
}

