import { IPhoneQuote } from './IPhoneQuote';
import { WholesaleCatalogue } from './WholesaleCatalogue.tsx';
import type { QuoteProduct } from './WholesaleQuoteBuilder';
import { wholesaleCatalogueUrl } from './wholesaleContact';
import { siteHref } from './sitePaths';
import type { EnquiryKind } from './EnquiryDialog';

type Props = { onEnquire: (kind: EnquiryKind, category?: string, issue?: string, phone?: import('./EnquiryDialog').RepairPhone, quoteItems?: QuoteProduct[]) => void };
import { accessoryCategories } from './accessoryChoices';

export function AccessoriesPage({ onEnquire }: Props) {
  return <><section className="hero repairs-hero"><div><p className="eyebrow">ITOP / ACCESSORIES</p><h1>Small things.<br />Big difference<span>.</span></h1></div><div className="hero-copy"><p>Protect it. Charge it. Make it yours.<br />Choose what you need. We’ll check the fit, current stock and price before you visit.</p><div className="accessory-hero-actions"><a className="button button-dark" href="#accessory-categories">Browse accessories</a><button className="text-button" onClick={() => onEnquire('Accessories')}>Help me choose</button></div></div></section>
    <nav className="accessory-shortcuts" aria-label="Browse accessory categories">{accessoryCategories.map(category => <a href={'#' + category.title.toLowerCase()} key={category.title}>{category.title}</a>)}</nav>
    <section className="accessories service-shelf" id="accessory-categories" aria-label="Accessory categories"><div className="product-grid">{accessoryCategories.map(category => <article className="product accessory-category" id={category.title.toLowerCase()} key={category.title}><button className="product-photo" onClick={() => onEnquire('Accessories', category.title)} aria-label={`Enquire about ${category.title.toLowerCase()}`}><img src={siteHref(`assets/${category.image}.webp`)} srcSet={`${siteHref(`assets/${category.image}-480.webp`)} 480w, ${siteHref(`assets/${category.image}-960.webp`)} 960w, ${siteHref(`assets/${category.image}.webp`)} 1448w`} sizes="(max-width:720px) calc(100vw - 48px), 33vw" width={1448} height={1086} loading="lazy" decoding="async" alt={`Illustrative ${category.title.toLowerCase()} accessories; current stock varies`} /></button><div className="product-copy"><h2>{category.title}</h2><p>{category.text}</p><div className="accessory-item-choices" role="group" aria-label={`${category.title} accessory choices`}>{category.items.map(item => <button key={item} onClick={() => onEnquire('Accessories', item)}>{item}<span aria-hidden="true">↗</span></button>)}</div><p className="accessory-photo-note">Illustrative photo · ask about current stock.</p></div></article>)}</div></section>
    <section className="content-section"><div><p className="eyebrow">THE RIGHT FIT</p><h2>Bring the model.<br />We’ll check the match.</h2></div><div className="service-notes"><p>A case needs the exact model. A cable needs the right connector. A charger needs to suit your device.</p><ul><li>Not sure of your model? We can help identify it.</li><li>Tell us the connector, colour and quantity you need.</li><li>Ask about tablet, laptop, watch or car accessories too.</li></ul><button className="text-button" onClick={() => onEnquire('Accessories')}>Ask about another accessory</button><a className="text-button accessory-delivery-link" href="https://deliveroo.co.uk/menu/london/catford/itop-phones-and-repair-center" target="_blank" rel="noopener noreferrer">Check the Deliveroo listing</a><p className="secondary-copy">Selected items may be available for delivery. Stock, delivery area and fees are shown by Deliveroo.</p></div></section>
  </>;
}

export function WholesalePage({ onEnquire }: Props) {
  return <><section className="hero repairs-hero wholesale-hero"><div><p className="eyebrow">ITOP / WHOLESALE</p><h1>Your shop.<br />Well supplied<span>.</span></h1></div><div className="hero-copy"><p>Find products, choose quantities and build a quote list for your shop or resale business.</p><div className="wholesale-actions"><a className="button button-dark" href="#wholesale-catalogue">Browse products</a><button className="text-button" onClick={() => onEnquire('Trade')}>Request a wholesale quote</button><a className="text-button" href={siteHref('wholesale/apply/')}>Apply for trade supply</a></div></div></section>
    <WholesaleCatalogue onReview={items=>onEnquire('Trade','',undefined,undefined,items)} />
    <section className="repair-band"><div className="repair-intro"><h2>From list<br />to agreed supply.</h2><p>Pricing and quantities are quoted for your enquiry.</p></div><ol className="repair-steps"><li><span>01</span><h3>Send</h3><p>Your products<br />and quantities.</p></li><li><span>02</span><h3>Review</h3><p>Stock, price<br />and options.</p></li><li><span>03</span><h3>Agree</h3><p>Collection<br />or delivery.</p></li></ol><button className="button button-cyan" onClick={() => onEnquire('Trade')}>Build a quote request</button></section>
    <section className="content-section"><div><p className="eyebrow">TRADE SUPPLY OR TEAM DEVICES?</p><h2>The right route.<br />For your business.</h2></div><div className="service-notes"><p>Buying products for resale? Introduce your business and tell us what you usually need.</p><a className="text-button" href={siteHref('wholesale/apply/')}>Start a trade application</a><p className="support-note">Need repairs, replacement devices or accessories for staff? Use iTop for Business.</p><a className="text-button" href={siteHref('business/')}>Explore iTop for Business</a></div></section>
    <section className="content-section repair-faq"><div><p className="eyebrow">TRADE QUESTIONS</p><h2>Before you<br />place an order.</h2></div><div className="faq-list"><details><summary>Is there a minimum order?</summary><p>Ask about the products and quantities you need. Minimum quantities, pack sizes and trade terms are confirmed with your quote.</p></details><details><summary>Where can I browse products?</summary><p>Search the product catalogue above and add items to your quote list. WhatsApp has the product photos and current prices. For products you cannot find, describe them in a wholesale quote request.</p></details><details><summary>Can you arrange delivery?</summary><p>Send your location and preferred date. Delivery options, charges and timing are confirmed before an order is agreed.</p></details></div></section>
  </>;
}

export function BuySellPage({ onEnquire }: Props) {
  return <><section className="hero repairs-hero"><div><p className="eyebrow">ITOP / BUY & SELL</p><h1>A new chapter.<br />For your tech<span>.</span></h1></div><div className="hero-copy"><p>Looking for your next device, or ready to move one on? Start with a conversation at iTop in Catford.</p><div className="device-hero-actions"><button className="button button-dark" onClick={() => onEnquire('Buy / sell', 'Buy a device')}>Buy a device</button><a className="button button-outline" href="#iphone-quote">Get an iPhone offer</a></div></div></section>
    <IPhoneQuote />
    <section className="device-options" id="device-options" aria-label="Buy or sell a device"><article><span className="eyebrow">01 / BUY</span><h2>Find your<br />next device.</h2><p>Tell us your preferred model, storage and budget. Ask about current used or refurbished devices and their condition.</p><button className="button button-dark" onClick={() => onEnquire('Buy / sell', 'Buy a device')}>Start a buying enquiry</button><p className="secondary-copy">Availability, condition and any warranty are confirmed for the individual device.</p></article><article><span className="eyebrow">02 / SELL</span><h2>See what<br />yours could be worth.</h2><p>Share the model, storage, condition and any faults. An offer depends on an in-store inspection and ownership checks.</p><button className="button button-dark" onClick={() => onEnquire('Buy / sell', 'Sell a device')}>Request a manual valuation</button><p className="secondary-copy">An enquiry is not a final valuation or a commitment to sell.</p></article></section>
    <section className="content-section"><div><p className="eyebrow">BEFORE YOUR VISIT</p><h2>Know your device.<br />Protect your data.</h2></div><div className="service-notes"><p>Back up your personal files before selling. Bring the device and any relevant accessories or proof of ownership.</p><ul><li>Tell us about damage, battery problems or repairs.</li><li>Ask the team about account and activation locks.</li><li>Discuss reset steps in-store once you agree to sell.</li><li>Never share account passwords or passcodes in your enquiry.</li></ul><a className="text-button" href={siteHref('contact/')}>Visit & Contact</a></div></section>
  </>;
}


